package(default_visibility = ["//visibility:public"])

java_library(
    name = "execution",
    srcs = glob(["**/*.java"]),
    deps = [
        "@com_google_guava_guava//jar",
        "@com_graphql_java//jar",
        "@future_converter//jar",
        "@future_converter_common//jar",
        "@future_converter_java8_common//jar",
        "@future_converter_guava_common//jar",        
    ],
)
