maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:23.5-jre",
)
maven_jar(
    name = "com_graphql_java",
    artifact = "com.graphql-java:graphql-java:6.0",
)
maven_jar(
    name = "future_converter",
    artifact = "net.javacrumbs.future-converter:future-converter-java8-guava:1.1.0"
)
