package com.google.api.graphql.rejoiner;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import javax.inject.Qualifier;

/** Annotates the {@link graphql.schema.GraphQLSchema} generated by Rejoiner. */
@Retention(RetentionPolicy.RUNTIME)
@Qualifier
public @interface Schema {}
